### PR TITLE
DECISION TREE

### PR DESCRIPTION
**Pull request by raviyaswanth**
I hope this helps the beginner's how to execute decision tree for classification

### CODE REVIEW

**Review by iam-abbas — CHANGES_REQUESTED** [review]
Could you do one small change for me? Since there are already two of these using libraries could you move them both to 
```
[root]/UsingModules/[Algo Name]/[Language]/
```

Thanks!

**Comment by raviyaswanth** [comment]
Can you please assist me how to move them , because I am a beginner and have no idea in this thing.

**Comment by iam-abbas** [comment]
Sure! First you need to clone your forked Repository on to your workstation/laptop then you move the files to respective folders requested above then commit to your forked repository. Finally make a PR just like you did now.



```

Fork -> Clone to PC -> Change/Move files on Your PC -> Commit to Fork -> PR

```


Hope you got it 😁

**Comment by raviyaswanth** [comment]
I am really sorry I was not able to do that . And I want to contribute 4 more different ML algorithms that I have learnt . Can I do them in the same way I did previous two?

**Comment by iam-abbas** [comment]
Hello if you are talking about Hacktoberfest.Then only **1 PR from 1 Repository Counts** That means only will only get 1 PR from this repository so there is no use of doing another. Please go on issuehub.io to find more opensource projects where you can contribute

**Comment by iam-abbas** [comment]
Closing this PR

**Pull request closed without merging**
