### PR TITLE
Added a notebook

### PR DESCRIPTION
**Pull request by agasheaditya**
The notebook contains logistic regression solved using Numpy as well as SKlearn using IRIS dataset.

### CODE REVIEW

**Review by iam-abbas — CHANGES_REQUESTED** [review]
Could you instead add this to [root]/Notebooks/UsingLibs/[file]

**Comment by agasheaditya** [comment]
okay sure @iam-abbas

**Comment by agasheaditya** [comment]
> Could you instead add this to [root]/Notebooks/UsingLibs/[file]

Hi @iam-abbas  I have made changes as you suggested. but I am unable to create PR. so please check the same. thanks

**Review by iam-abbas — APPROVED** [review]
Excellent!

**Pull request merged**
